package Entrega2;


//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Thu Apr 18 10:13:36 PDT 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TSTRING = 44;
  public static final int MULT = 32;
  public static final int CONDI = 19;
  public static final int PARENCuaI = 49;
  public static final int PARENRedI = 46;
  public static final int PRINTLN = 16;
  public static final int PARENCuaD = 48;
  public static final int OUT = 15;
  public static final int CICLO = 18;
  public static final int PARENRedD = 47;
  public static final int STATIC = 8;
  public static final int MENORIGUAL = 40;
  public static final int AND = 35;
  public static final int SINO = 20;
  public static final int PUNTOyCOMA = 4;
  public static final int IN = 21;
  public static final int OR = 34;
  public static final int TBOOL = 45;
  public static final int CLASS = 17;
  public static final int COMPA = 37;
  public static final int DIV = 31;
  public static final int NUM = 54;
  public static final int SUMA = 29;
  public static final int EXIT = 23;
  public static final int MAIN = 10;
  public static final int THIS = 27;
  public static final int ID = 53;
  public static final int MAYORIGUAL = 41;
  public static final int EOF = 0;
  public static final int SYSTEM = 14;
  public static final int RETURN = 13;
  public static final int TRUE = 25;
  public static final int NEW = 28;
  public static final int error = 1;
  public static final int COMA = 2;
  public static final int MENOR = 39;
  public static final int VOID = 9;
  public static final int PARENCurI = 51;
  public static final int MAYOR = 42;
  public static final int IMPORT = 6;
  public static final int PARENCurD = 50;
  public static final int TINT = 43;
  public static final int NEG = 36;
  public static final int REST = 30;
  public static final int PUNTOyASTERISCO = 5;
  public static final int PUNTO = 3;
  public static final int READ = 22;
  public static final int PUBLIC = 7;
  public static final int EXTENDS = 11;
  public static final int ASIGN = 33;
  public static final int STRING = 52;
  public static final int DIFE = 38;
  public static final int FALSE = 26;
  public static final int IMPLEMENTS = 12;
  public static final int LENGTH = 24;
}

