package Entrega2;
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Mon Apr 08 22:57:31 CST 2013
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int TSTRING = 47;
  public static final int MULT = 33;
  public static final int CONDI = 20;
  public static final int PARENCuaI = 52;
  public static final int PARENRedI = 49;
  public static final int PRINTLN = 17;
  public static final int PARENCuaD = 51;
  public static final int OUT = 16;
  public static final int CICLO = 19;
  public static final int PARENRedD = 50;
  public static final int STATIC = 9;
  public static final int MENORIGUAL = 41;
  public static final int AND = 36;
  public static final int SINO = 21;
  public static final int PUNTOyCOMA = 5;
  public static final int OR = 35;
  public static final int IN = 22;
  public static final int TBOOL = 48;
  public static final int CLASS = 18;
  public static final int COMPA = 38;
  public static final int DIV = 32;
  public static final int NUM = 2;
  public static final int SUMA = 30;
  public static final int EXIT = 24;
  public static final int MAIN = 11;
  public static final int THIS = 28;
  public static final int ID = 45;
  public static final int MAYORIGUAL = 42;
  public static final int EOF = 0;
  public static final int SYSTEM = 15;
  public static final int RETURN = 14;
  public static final int TRUE = 26;
  public static final int NEW = 29;
  public static final int error = 1;
  public static final int COMA = 3;
  public static final int MENOR = 40;
  public static final int VOID = 10;
  public static final int PARENCurI = 54;
  public static final int MAYOR = 43;
  public static final int IMPORT = 7;
  public static final int PARENCurD = 53;
  public static final int TINT = 46;
  public static final int NEG = 37;
  public static final int REST = 31;
  public static final int PUNTOyASTERISCO = 6;
  public static final int PUNTO = 4;
  public static final int READ = 23;
  public static final int PUBLIC = 8;
  public static final int EXTENDS = 12;
  public static final int ASIGN = 34;
  public static final int STRING = 44;
  public static final int DIFE = 39;
  public static final int FALSE = 27;
  public static final int IMPLEMENTS = 13;
  public static final int LENGTH = 25;
}

